export const bubbleTeas = [
  {
    id: 1,
    name: "bubble tea 1",
    price: "$5",
    image: "bubbletea1.jpg",
    gradient: "fruit tea",
  },
  {
    id: 2,
    name: "bubble tea 2",
    price: "$5",
    image: "bubbletea2.jpg",
    gradient: "fruit tea",
  },
  {
    id: 3,
    name: "bubble tea 3",
    price: "$5",
    image: "bubbletea3.jpg",
    gradient: "fruit tea",
  },
  {
    id: 4,
    name: "bubble tea 4",
    price: "$5",
    image: "bubbletea4.jpg",
    gradient: "black tea",
  },
  {
    id: 5,
    name: "bubble tea 5",
    price: "$5",
    image: "bubbletea5.jpg",
    gradient: "green tea",
  },
  {
    id: 6,
    name: "bubble tea 6",
    price: "$5",
    image: "bubbletea6.png",
    gradient: "fruit tea",
  },
  {
    id: 7,
    name: "bubble tea 7",
    price: "$5",
    image: "bubbletea7.png",
    gradient: "fruit tea",
  },
  {
    id: 8,
    name: "bubble tea 8",
    price: "$5",
    image: "bubbletea8.png",
    gradient: "fruit tea",
  },
  {
    id: 9,
    name: "bubble tea 9",
    price: "$5",
    image: "bubbletea9.png",
    gradient: "fruit tea",
  },
];
